tap "homebrew/bundle"
tap "homebrew/services"
tap "ngrok/ngrok"
tap "twilio/brew"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Distributed revision control system
brew "git"
# Add indentation to LaTeX files
brew "latexindent"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12", link: false
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Menu bar tool to limit maximum charging percentage
cask "aldente"
# Full TeX Live distribution without GUI applications
cask "mactex-no-gui"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
vscode "akamud.vscode-theme-onedark"
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-containers"
vscode "arcanis.vscode-zipfs"
vscode "bierner.markdown-checkbox"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bierner.markdown-yaml-preamble"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "dotenv.dotenv-vscode"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "github.vscode-pull-request-github"
vscode "graphql.vscode-graphql-syntax"
vscode "ibm.output-colorizer"
vscode "james-yu.latex-workshop"
vscode "kamikillerto.vscode-colorize"
vscode "mrmlnc.vscode-scss"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "mtxr.sqltools"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "streetsidesoftware.code-spell-checker"
vscode "stylelint.vscode-stylelint"
vscode "vitest.explorer"
vscode "vscode-icons-team.vscode-icons"
vscode "yoavbls.pretty-ts-errors"
